apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lk-tnsw.frontend.fullname" . }}
  labels:
    {{- include "lk-tnsw.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "lk-tnsw.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lk-tnsw.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.frontend.image.repository }}:{{ include "lk-tnsw.imageTag" (dict "tag" .Values.frontend.image.tag "root" .) }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          {{- if .Values.frontend.env }}
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              {{- if kindIs "map" $value }}
              {{- toYaml $value | nindent 14 }}
              {{- else }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.frontend.envFrom }}
          envFrom:
            {{- toYaml .Values.frontend.envFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.resources }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
          {{- if or .Values.frontend.branding .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- if .Values.frontend.branding }}
            - name: branding
              mountPath: /usr/share/nginx/html/configs/branding.json
              subPath: branding.json
            {{- end }}
            {{- if .Values.frontend.volumeMounts }}
            {{- toYaml .Values.frontend.volumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.frontend.branding .Values.frontend.volumes }}
      volumes:
        {{- if .Values.frontend.branding }}
        - name: branding
          configMap:
            name: {{ include "lk-tnsw.frontend.fullname" . }}-branding
        {{- end }}
        {{- if .Values.frontend.volumes }}
        {{- toYaml .Values.frontend.volumes | nindent 8 }}
        {{- end }}
      {{- end }}
